### ISSUE TITLE
Inserted Images from FileSafe do not persist

### ISSUE THREAD

**Issue by adamcarchibald** [standardnotes/bold-editor#32] opened 2020-06-30 16:09 UTC
When inserting an encrypted attached file from FileSafe in a note using Bold Editor.  The change is not persistent after you navigate away from the note.

Same behaviour in MacOS and Android versions and GoogleDrive as the storage location

![bug-example](https://user-images.githubusercontent.com/16963265/86149728-5fb3cb00-baca-11ea-8865-fa3b3f492ec6.gif)

**Comment by ningsongshen** [comment] 2020-06-30 19:10
@adamcarchibald thanks for reporting this (video is very helpful)! 

This is a known issue and work is ongoing for more robust image saving.

**Comment by mobitar** [comment] 2020-06-30 21:53
@ningsongshen this is a known issue? What do you mean? Images should definitely persist; there shouldn't be any issues here. If instead the issue is that if you insert an image and then immediately toggle code view, then switch notes, then maybe that is a separate issue of its own.

**Comment by ningsongshen** [comment] 2020-07-02 18:14
Yup this is a known issue. 

Back when you were developing the editor, you left a [helpful comment](https://github.com/standardnotes/bold-editor/blob/master/app/components/Editor.js#L49) that I took note of when testing. :smiley: 

It is also essentially the same issue as detected here: https://github.com/standardnotes/bold-editor/issues/17#issuecomment-631641398 because the images/figure tags are not being loaded into FileSafe. 

And so I am going to submit a draft PR to think about solutions that could fix this. (in the last PR I tried removing figure tags, which worked, but had an undesirable side effect of disabling resizing)

**Comment by mobitar** [comment] 2020-07-03 14:06
We've went back to a release of Bold Editor that did not have this issue (released as a new version 1.0.9). We'll be spending more time investigating which update exactly caused this issue, but we're sure now not to release another version with this behavior.

**Closed by mobitar** 2020-07-03 14:06 UTC
Labels: bug
